browser=chromium
headless=false
slowMo=100
timeout=30000
baseUrl=https://automationpracticehub.com/
username=sagesyntaxacademy
password=BuildingExcellence@111
screenshotOnPass=false
screenshotOnFail=true
recordVideo=true
trace=true
#lambdatest
LambdaTestUsername=MohammadHassan
LambdaTestAccessKey=LT_AZIzVStplouCaR76M6miYsUBgF2ttc7AYpQal1yejYkUEr8
TunnelName=Dell-3rwbaaii2so
AutomationType=UIAutomation
ExecutionType=Remote
TestBrowserForUIAutomation=GoogleChrome
TestrailReadTestCase=true
UpdateTestRail=false
UpdateLambda=true
ProjectName=PlaywrightProject
projectName=PlaywrightProject
BuildName=PlaywrightIntegration
##Testrail
projectID=2
TestPlanID=126
TestRunID=127
TestRailUsername=mohammad.hassan@tatacapital.com
TestRailPassword=Tata@123
TestRailEngineURL=https://tatacapital.testrail.io/index.php?/
TestRailAPIProjectNameURL=https://tatacapital.testrail.io/index.php?/api/v2/get_project/
