browser=chromium
headless=false
slowMo=100
timeout=30000
baseUrl=https://automationpracticehub.com/
username=sagesyntaxacademy
password=BuildingExcellence@111
screenshotOnPass=false
screenshotOnFail=true
recordVideo=true
trace=true
#lambdatest
Username=guptamandeep505
AccessKey=LT_et16lfAp5cA2KIvihuXSQSjVpVcqa8PeTCpAkN7VbvqUbwQ
TunnelName=Dell-jry499425q
AutomationType=UIAutomation
ExecutionType=Remote
TestBrowserForUIAutomation=GoogleChrome
TestrailReadTestCase=true
UpdateTestRail=true
UpdateLambda=true
ProjectName=Sagesyntax
projectName=Sagesyntax
BuildName=SagesyntaxBuild
##Testrail
projectID=2
TestPlanID=15
TestRunID=16
TestRailUsername=garimasaxena63@gmail.com
TestRailPassword=Garimaaaa63@
TestRailEngineURL=https://garimasaxena63.testrail.io/index.php?/
TestRailAPIProjectNameURL=https://garimasaxena63.testrail.io/index.php?/api/v2/get_project/
