browser=chromium
headless=false
slowMo=100
timeout=30000
baseUrl=https://automationpracticehub.com/
username=sagesyntaxacademy
password=BuildingExcellence@111
screenshotOnPass=false
screenshotOnFail=true
recordVideo=true
trace=true
#lambdatest
LambdaTestUsername=lambdatest_username
LambdaTestAccessKey=lambdatest_AccessKey
TunnelName=Dell-8g8voqbjvg
AutomationType=UIAutomation
ExecutionType=Local
TestBrowserForUIAutomation=GoogleChrome
TestrailReadTestCase=false
UpdateTestRail=false
UpdateLambda=false
ProjectName=PlaywrightProject
projectName=PlaywrightProject
BuildName=PlaywrightIntegration
##Testrail
projectID=2
TestPlanID=126
TestRunID=127
TestRailUsername=abc@abc.com
TestRailPassword=Tata@123
TestRailEngineURL=https://abc.testrail.io/index.php?/
TestRailAPIProjectNameURL=https://abc.testrail.io/index.php?/api/v2/get_project/
#node runner/TestRunner.js --env=qa --browser=chromium --parallel=1 --tags=@C5948