browser=firefox
headless=true
slowMo=0
timeout=30000

baseUrl=https://automationpracticehub.com/

username=sagesyntaxacademy
password=BuildingExcellence@111

screenshotOnPass=false
screenshotOnFail=true

recordVideo=false

trace=true